create table if not exists public.visitor_sessions (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  consent_status text not null check (consent_status in ('granted', 'denied', 'timeout', 'unsupported')),
  latitude double precision,
  longitude double precision,
  accuracy_meters integer,
  coarse_country text,
  coarse_region text,
  coarse_city text,
  browser_name text,
  os_name text,
  device_type text,
  user_agent_summary text,
  locale text,
  timezone text,
  viewport_width integer,
  viewport_height integer,
  screen_width integer,
  screen_height integer,
  referrer text,
  ip_hash text
);

create index if not exists visitor_sessions_created_at_idx
  on public.visitor_sessions (created_at desc);

create index if not exists visitor_sessions_consent_status_idx
  on public.visitor_sessions (consent_status);

alter table public.visitor_sessions enable row level security;
