create table if not exists public.visitor_sessions (
  id integer generated by default as identity primary key
);

alter table public.visitor_sessions
  add column if not exists created_at timestamptz,
  add column if not exists consent_status text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists accuracy_meters integer,
  add column if not exists coarse_country text,
  add column if not exists coarse_region text,
  add column if not exists coarse_city text,
  add column if not exists browser_name text,
  add column if not exists os_name text,
  add column if not exists device_type text,
  add column if not exists user_agent_summary text,
  add column if not exists locale text,
  add column if not exists timezone text,
  add column if not exists viewport_width integer,
  add column if not exists viewport_height integer,
  add column if not exists screen_width integer,
  add column if not exists screen_height integer,
  add column if not exists referrer text,
  add column if not exists ip_hash text;

alter table public.visitor_sessions
  alter column created_at set default timezone('utc'::text, now());

update public.visitor_sessions
set created_at = timezone('utc'::text, now())
where created_at is null;

update public.visitor_sessions
set consent_status = 'unsupported'
where consent_status is null
   or consent_status not in ('granted', 'denied', 'timeout', 'unsupported');

alter table public.visitor_sessions
  alter column created_at set not null,
  alter column consent_status set not null;

alter table public.visitor_sessions
  drop constraint if exists visitor_sessions_consent_status_check;

alter table public.visitor_sessions
  add constraint visitor_sessions_consent_status_check
  check (consent_status in ('granted', 'denied', 'timeout', 'unsupported'));

create index if not exists visitor_sessions_created_at_idx
  on public.visitor_sessions (created_at desc);

create index if not exists visitor_sessions_consent_status_idx
  on public.visitor_sessions (consent_status);

alter table public.visitor_sessions enable row level security;

notify pgrst, 'reload schema';
